\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {1}{\ignorespaces Initial timelapse preprocessing steps}}{39}{}%
\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {2}{\ignorespaces Labelled training data examples}}{40}{}%
\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {3}{\ignorespaces Preprocessing effects on pixel intensity distributions}}{41}{}%
\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {4}{\ignorespaces Methodology illustrations}}{42}{}%
