\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {1}{\ignorespaces Initial timelapse preprocessing steps}}{25}{}%
\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {2}{\ignorespaces Axon growth cone labelling}}{26}{}%
\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {3}{\ignorespaces Labelled training data examples}}{27}{}%
\defcounter {refsection}{0}\relax 
\contentsline {suppfigure}{\numberline {4}{\ignorespaces Axon reconstruction from growth cone track}}{28}{}%
